/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Soe
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonBorder();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Menu index = new Menu();
    @SuppressWarnings("unchecked")
    public void buttonBorder(){
        btnReturn.setOpaque(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.setBorderPainted(false);
        sldVol.setOpaque(false);
        btnApply.setOpaque(false);
        btnApply.setContentAreaFilled(false);
        btnApply.setBorderPainted(false);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApply = new javax.swing.JButton();
        sldVol = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(580, 510));
        setMinimumSize(new java.awt.Dimension(580, 510));
        getContentPane().setLayout(null);

        btnApply.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        btnApply.setForeground(new java.awt.Color(255, 255, 255));
        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnApply);
        btnApply.setBounds(340, 430, 110, 40);

        sldVol.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        sldVol.setForeground(new java.awt.Color(255, 255, 255));
        sldVol.setMajorTickSpacing(25);
        sldVol.setMinorTickSpacing(25);
        sldVol.setPaintLabels(true);
        sldVol.setPaintTicks(true);
        sldVol.setToolTipText("0");
        sldVol.setValue(100);
        sldVol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sldVol.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVolStateChanged(evt);
            }
        });
        getContentPane().add(sldVol);
        sldVol.setBounds(160, 140, 200, 46);

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Volumen:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 160, 80);

        btnReturn.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn);
        btnReturn.setBounds(460, 430, 120, 40);

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Options");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, -10, 190, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/black_texture___ray_by_ethenyl.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-790, -410, 1370, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // RETURN
        index.sound("popup+runtitle");
        this.dispose();
        index.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void sldVolStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVolStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sldVolStateChanged

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
        Aviso alert = new Aviso();
        alert.setVisible(true);
    }//GEN-LAST:event_btnApplyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider sldVol;
    // End of variables declaration//GEN-END:variables
}
