/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import vista.Menu;

/**
 *
 * @author Soe
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opciones
     */
    public Opciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        buttonBorder();
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    Menu index = new Menu();
    @SuppressWarnings("unchecked")
    public void buttonBorder(){
        btnReturn.setOpaque(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.setBorderPainted(false);
        sldVol.setOpaque(false);
        btnApply.setOpaque(false);
        btnApply.setContentAreaFilled(false);
        btnApply.setBorderPainted(false);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnApply = new javax.swing.JButton();
        sldVol = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Resolution1 = new javax.swing.JLabel();
        BigR = new javax.swing.JButton();
        MidR = new javax.swing.JButton();
        SmaR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(580, 510));
        setMinimumSize(new java.awt.Dimension(580, 510));
        getContentPane().setLayout(null);

        btnApply.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        btnApply.setForeground(new java.awt.Color(255, 255, 255));
        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });
        getContentPane().add(btnApply);
        btnApply.setBounds(340, 430, 110, 40);

        sldVol.setFont(new java.awt.Font("Sylfaen", 1, 11)); // NOI18N
        sldVol.setForeground(new java.awt.Color(255, 255, 255));
        sldVol.setMajorTickSpacing(25);
        sldVol.setMinorTickSpacing(25);
        sldVol.setPaintLabels(true);
        sldVol.setPaintTicks(true);
        sldVol.setToolTipText("0");
        sldVol.setValue(100);
        sldVol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sldVol.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldVolStateChanged(evt);
            }
        });
        getContentPane().add(sldVol);
        sldVol.setBounds(160, 140, 200, 46);

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Volumen:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 160, 80);

        btnReturn.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn);
        btnReturn.setBounds(460, 430, 120, 40);

        Title.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Options");
        getContentPane().add(Title);
        Title.setBounds(190, -10, 190, 110);

        Resolution1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        Resolution1.setForeground(new java.awt.Color(255, 0, 255));
        Resolution1.setText("Resolution:");
        getContentPane().add(Resolution1);
        Resolution1.setBounds(10, 240, 220, 70);

        BigR.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        BigR.setForeground(new java.awt.Color(255, 0, 255));
        BigR.setText("800x600");
        BigR.setContentAreaFilled(false);
        BigR.setOpaque(false);
        BigR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BigRActionPerformed(evt);
            }
        });
        getContentPane().add(BigR);
        BigR.setBounds(260, 370, 160, 40);

        MidR.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        MidR.setForeground(new java.awt.Color(255, 0, 255));
        MidR.setText("1280X960");
        MidR.setContentAreaFilled(false);
        MidR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MidRActionPerformed(evt);
            }
        });
        getContentPane().add(MidR);
        MidR.setBounds(260, 250, 165, 40);

        SmaR.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        SmaR.setForeground(new java.awt.Color(255, 0, 255));
        SmaR.setText("1152x864");
        SmaR.setContentAreaFilled(false);
        SmaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SmaRActionPerformed(evt);
            }
        });
        getContentPane().add(SmaR);
        SmaR.setBounds(260, 310, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/black_texture___ray_by_ethenyl.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-790, -410, 1370, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // RETURN
        index.sound("popup+runtitle");
        this.dispose();
        index.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    private void sldVolStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldVolStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sldVolStateChanged

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        // TODO add your handling code here:
        Aviso alert = new Aviso();
        alert.setVisible(true);
    }//GEN-LAST:event_btnApplyActionPerformed

    private void BigRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BigRActionPerformed
        // TODO add your handling code here:
        Menu sizeW = new Menu();
        sizeW.setSize(1280,960);
    }//GEN-LAST:event_BigRActionPerformed

    private void MidRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MidRActionPerformed
        // TODO add your handling code here:
        Menu sizeW = new Menu();
        sizeW.setSize(1152,864);
    }//GEN-LAST:event_MidRActionPerformed

    private void SmaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SmaRActionPerformed
        // TODO add your handling code here:
        Menu sizeW = new Menu();
        sizeW.setSize(800,600);
    }//GEN-LAST:event_SmaRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Opciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BigR;
    private javax.swing.JButton MidR;
    private javax.swing.JLabel Resolution1;
    private javax.swing.JButton SmaR;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider sldVol;
    // End of variables declaration//GEN-END:variables
}
